### PR TITLE
[YUNIKORN-325] feat: implement node resource utilization chart

### PR DESCRIPTION
**Pull request by stu01509**
### What is this PR for?
- Implement the `Bar Chart` component.
- Implement node resource utilization chart.
- Add `nodes/utilization` mock API.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [x] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
[YUNIKORN-325](https://issues.apache.org/jira/browse/YUNIKORN-325)

### Screenshots (if appropriate)
image

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by craigcondit** [comment]
I think this info would be better displayed as a histogram rather than a circle chart. With the circle chart, the legend is 100% necessary to interpret the results, whereas a histogram will be fairly obvious (chart the percentage (bucket) along the bottom, and the count as the height of the bar).

**Comment by stu01509** [comment]
Hi @craigcondit, @wilfred-s 

Thanks for your comments, Could we use the third-party chart library like ECharts or Chart.js? 
Because the current donut chart is built by ourselves, I think it would be more difficult to maintain.


- https://www.chartjs.org/
- https://echarts.apache.org/en/index.html

**Comment by stu01509** [comment]
HI @craigcondit , @wilfred-s 

Update the commit, Please help to review.

**Review by wilfred-s — APPROVED** [review]
LGTM
@craigcondit any further remarks from your side?

**Pull request closed without merging**
