### PR TITLE
[YUNIKORN-2437] Include NOTICE and LICENSE files in Docker image

### PR DESCRIPTION
**Pull request by craigcondit**
### What is this PR for?
Ensure that yunikorn-web contains the project's NOTICE and LICENSE files.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [x ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2437

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by pbacsko — APPROVED** [review]
+1

**Comment by chia7712** [comment]
Do we consider following OCI annotations to add license? https://github.com/opencontainers/image-spec/blob/main/annotations.md

**Review by wilfred-s — APPROVED** [review]
LGTM

**Comment by wilfred-s** [comment]
@chia7712 that is a much larger ask/change. We would need to think about to what we attach them, which ones we attach etc. Please log a jira so we can track discuss there.

**Pull request closed without merging**
