### PR TITLE
[YUNIKORN-2885] Fix security vulnerabilities in dependencies

### PR DESCRIPTION
**Pull request by SP12893678**
### What is this PR for?
Fix security vulnerabilities in dependencies

`pnpm audit` report: [audit-report.md](https://github.com/user-attachments/files/17089735/audit-report.md)
26 vulnerabilities found
Severity: 12 moderate | 14 high

After Upgrade Angular v18 Audit Report: [audit-report.md](https://github.com/user-attachments/files/17164041/audit-report.md)
8 vulnerabilities found
Severity: 3 moderate | 5 high

### What type of PR is it?
* [x] - Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2885

### How should this be tested?
Run `pnpm audit`
Expected Output: No known vulnerabilities found

### CODE REVIEW

**Comment by chenyulin0719** [comment]
There have another PR about uprading Angular to v18.  We might need to recheck the vulnerabilities after it got merged.
- https://github.com/apache/yunikorn-web/pull/203/files

**Review by chenyulin0719 — CHANGES_REQUESTED** [review]
Hi @SP12893678,

We just upgraded Angular to v18.  The vulnerabilities number is reduced from 26 to 8.
Could you rebase this PR and check vulnerabilities again?

```
8 vulnerabilities found
Severity: 3 moderate | 5 high
```

**Comment by SP12893678** [comment]
> Hi @SP12893678,
> 
> We just upgraded Angular to v18. The vulnerabilities number is reduced from 26 to 8. Could you rebase this PR and check vulnerabilities again?
> 
> ```
> 8 vulnerabilities found
> Severity: 3 moderate | 5 high
> ```

 Sure, I have updated.

**Review by chenyulin0719 — APPROVED** [review]
+1 LGTM

**Review by ryankert01 — APPROVED** [review]
lgtm

**Pull request closed without merging**
