### PR TITLE
[YUNIKORN-2958] Display foreign allocations on the web UI

### PR DESCRIPTION
**Pull request by pbacsko**
### What is this PR for?
Display foreign allocations on the Nodes page.

Notes:
1. The PR fetches both YK & non-YK allocations and combine them in a single list
2. New "type" field is added
3. An icon is rendered in a separate "type" column based on whether it's a Yunikorn or foreign pod.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [x] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2958

### Screenshots (if appropriate)
view2
view1

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by craigcondit — CHANGES_REQUESTED** [review]
A couple of things:

I don't think we want to show all the attributes unless we're in expanded view, otherwise this is going to get really ugly with lots of nodes. In fact, I'd opt to hide the attributes column entirely unless we're expanded. It's just not relevant 99% of the time.

I also don't think we should add a Kubernetes-specific icon (as at least in theory, the web UI is agnostic).

**Comment by pbacsko** [comment]
I decided not to use icons in the "Type" column. I've been unable to find a nice pair of arrow icons. Sometimes copyright is an issue because it's too prohibitive. I was thinking about calling it "Scheduled by Yunikorn", with a checkmark indicating a YK pod and an external link indicating a foreign pod, but ultimately it's just too much hassle. I've already spent hours with it.

Let's use a text field, this can be improved any time later on.

**Comment by pbacsko** [comment]
Rendered pages with the latest commit
foreign_text
yk_text

**Comment by pbacsko** [comment]
> I don't think we want to show all the attributes unless we're in expanded view, otherwise this is going to get really ugly with lots of nodes. In fact, I'd opt to hide the attributes column entirely unless we're expanded. It's just not relevant 99% of the time.

Created https://issues.apache.org/jira/browse/YUNIKORN-2970. On my browser, it's displayed by default, but after clicking on "..." twice it disappears. This makes me think that it's supposed to be displayed only in enhanced mode.

**Comment by craigcondit** [comment]
I think we should just remove the 'type' column. YuniKorn allocations can be easily discerned by the presence of the Application ID field.

**Comment by pbacsko** [comment]
> I think we should just remove the 'type' column. YuniKorn allocations can be easily discerned by the presence of the Application ID field.

Makes sense. I'll catch up with Wilfred tomorrow morning. This would further simplify the changes.

**Pull request closed without merging**
