### PR TITLE
[YUNIKORN-2480] Convert yunikorn-web to use pnpm

### PR DESCRIPTION
**Pull request by craigcondit**
### What is this PR for?
Switch to pnpm instead of yarn for nodejs builds. This is much more performant and has better dependency resolution rules.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2480

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by chenyulin0719 — CHANGES_REQUESTED** [review]
Most of the changes look good. Below commands successed in my env.
- make start-dev
- make clean image 
- make test
- pnpm start
- pnpm start:srv

@craigcondit  Could you also update 'yarn' commands and dependencies description in README.md?
- https://github.com/apache/yunikorn-web?tab=readme-ov-file#dependencies
- https://github.com/apache/yunikorn-web?tab=readme-ov-file#running-tests

**Review by chenyulin0719 — CHANGES_REQUESTED** [review]
I think we should change 'yarn' to 'pnpm' in angular.json too.
- https://github.com/apache/yunikorn-web/blob/master/angular.json#L5

**Comment by craigcondit** [comment]
> @craigcondit Could you also update 'yarn' commands and dependencies description in README.md?
>     * [apache/yunikorn-web#dependencies](https://github.com/apache/yunikorn-web?tab=readme-ov-file#dependencies)
>     * [apache/yunikorn-web#running-tests](https://github.com/apache/yunikorn-web?tab=readme-ov-file#running-tests)
Updated in latest commit.

**Review by chenyulin0719 — APPROVED** [review]
+1 LGTM

**Pull request closed without merging**
