### PR TITLE
[YUNIKORN-2047] Remove duplicate colour in app state donut

### PR DESCRIPTION
**Pull request by targetoee**
### What is this PR for?
Currently, there are 11 states, but there are only 4 color codes in the donut graph. As a result, some states have the same color, which can be confusing at times. This PR adds more color codes to make it easier to distinguish between different states in the donut graph. The updated appearance is displayed below.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?
[YUNIKORN-2047](https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-2047)

### Screenshots (if appropriate)

|||
|----|---|

### CODE REVIEW

**Review by wilfred-s — CHANGES_REQUESTED** [review]
Only one comment: we should re-use the same colours as we use in #136 for some unity in the UI. The colours used in that PR are slightly different, choices can be made but I think limiting the colours is a good idea
List of colours used in the chart:
-  '#4285f4'
- '#db4437'
- '#f4b400'
- '#0f9d58'
- '#ff6d00'
- '#3949ab'
- '#facc54'
- '#26bbf0'
- '#cc6164'
- '#60cea5'

**Comment by wilfred-s** [comment]
With the addition of the bar chart for the node utilisation this PR will also need a rebase to resolve the conflicts

**Comment by targetoee** [comment]
Hi @wilfred-s thanks for your advice. I've updated the color code. Please take a look.

|||
|---|---|
|||

**Review by wilfred-s — APPROVED** [review]
LGTM

**Pull request closed without merging**
