### PR TITLE
[YUNIKORN-2723] Handle long queue names in QueuesV2 (Beta) page

### PR DESCRIPTION
**Pull request by SP12893678**
### What is this PR for?
Append wordwrap queuename in QueuesV2 (Beta) page

### What type of PR is it?
* [x] - Bug Fix

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2723

### Screenshots (if appropriate)
| Before | ~~Wordwrap~~ | Ellipsis & Tooltip |
|  ----  | ----  | ----  |
|  image | image | <video src="https://github.com/user-attachments/assets/f404115a-1ccc-4344-8049-e87f5ecd2ad9"> |

### CODE REVIEW

**Comment by craigcondit** [comment]
I think it would be far better to *not* wrap the queue name, and instead use ellipsis at the beginning. For example, if queue is `root.level1.level2.level3.level4`, this could be displayed as `...level3.level4` or something, and then have a hover tooltip with the full queue name.

**Comment by SP12893678** [comment]
> I think it would be far better to _not_ wrap the queue name, and instead use ellipsis at the beginning. For example, if queue is `root.level1.level2.level3.level4`, this could be displayed as `...level3.level4` or something, and then have a hover tooltip with the full queue name.
> 
> Alternatively, the queues could be displayed with their short names, since we already show the tree:
> 
> ```
> root ->
>   level1 ->
>     level2 ->
>       level3 ->
>         level4
> ```

Sounds great. it will not consider card dynamic height problem.
I have updated it to use Ellipsis and Tooltip, as shown above.

**Comment by craigcondit** [comment]
> > I think it would be far better to _not_ wrap the queue name, and instead use ellipsis at the beginning. For example, if queue is `root.level1.level2.level3.level4`, this could be displayed as `...level3.level4` or something, and then have a hover tooltip with the full queue name.
> > Alternatively, the queues could be displayed with their short names, since we already show the tree:
> > ```
> > root ->
> >   level1 ->
> >     level2 ->
> >       level3 ->
> >         level4
> > ```
> 
> Sounds great. it will not consider card dynamic height problem. I have updated it to use Ellipsis and Tooltip, as shown above.

I guess I wasn't very clear. Each queue has a parent queue, so a queue such as `root.level1.level2.level3.level4` needs to only show `level4` in the tree (in other words, only the last component after the final period). When shown in a graph, there's no need to display the fully-qualified queue name, only the short version. That component might still be too wide, so truncating with ellipsis and a tooltip is still useful, but shouldn't be necessary most of the time.

**Comment by SP12893678** [comment]
> I guess I wasn't very clear. Each queue has a parent queue, so a queue such as `root.level1.level2.level3.level4` needs to only show `level4` in the tree (in other words, only the last component after the final period). When shown in a graph, there's no need to display the fully-qualified queue name, only the short version. That component might still be too wide, so truncating with ellipsis and a tooltip is still useful, but shouldn't be necessary most of the time.

Okay, I got it!
I have updated it, as shown above video.

**Comment by SP12893678** [comment]
> The test coverage steps seem to be broken by this change.

oh, miss handle queueName undefined or null case
I have fixed it.

**Pull request closed without merging**
