### PR TITLE
[YUNIKORN-2506] fix deprecation warning for fontsource-roboto

### PR DESCRIPTION
**Pull request by ryankert01**
### What is this PR for?
migrate to @fontsource/roboto since the original fontsource-roboto is deprecated.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?

[YUNIKORN-2506](https://issues.apache.org/jira/browse/YUNIKORN-2506)

### How should this be tested?

```
make
```
```
make start-dev
```

### CODE REVIEW

**Comment by chenyulin0719** [comment]
I can't see the deprecation warning after run 'make' in yunikorn/master branch.  Did you successfully reproduce the warning?

**Comment by ryankert01** [comment]
@chenyulin0719 Not yet, but referring to [fontsource-roboto](https://www.npmjs.com/package/fontsource-roboto), it's best to migrate to @fontsource/roboto since it's depracation.

**Comment by chenyulin0719** [comment]
A small suggestion, I recommand that you can create PR from your forked branch so that we can easily checkout to your branch and validate it.
- "Recommendation is to use a fork of the repository and create a branch in your fork." https://yunikorn.apache.org/community/how_to_contribute/#create-a-pull-request

**Review by chenyulin0719 — APPROVED** [review]
+1 LGTM, I have no doubt about removing the deprecated package. 

@wilfred-s  Just for my curiosity, if you don't mind, could you let us know how to reproduce the deprecated warning.

**Comment by chenyulin0719** [comment]
Btw, there is no 'pnpm serve' command defined in package.json.  I ran the test through 'make start-dev'.

**Comment by ryankert01** [comment]
> Btw, there is no 'pnpm serve' command defined in package.json. I ran the test through 'make start-dev'.

That's true, my bad. Updated the pr.

**Pull request closed without merging**
