### PR TITLE
[YUNIKORN-2214] add sorting functionality to the Allocation view

### PR DESCRIPTION
**Pull request by vinayakphegde**
### What is this PR for?
Adding sorting functionality to Allocation View.  

### What type of PR is it?
* [x] - Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2214 

### How should this be tested?
Manually tested

### Screenshots (if appropriate)
Application Page
Screenshot 2023-12-01 at 10 40 43 PM

Node Page
Screenshot 2023-12-01 at 10 41 03 PM

### CODE REVIEW

**Comment by wilfred-s** [comment]
This adds sorting to all columns if I am not mistaken, please confirm if that is the case and we can commit if it is.

**Comment by chia7712** [comment]
I will test it manually later. @chenyulin0719  could you help me do double check?

**Comment by vinayakphegde** [comment]
Yes, it will add sorting to all columns.

**Review by chia7712 — APPROVED** [review]
LGTM

**Review by chenyulin0719 — COMMENTED** [review]
Hi @vinayakphegde ,
Validate that we can sort all columns now.

However, I find the sorting results a bit strange. 
When sorting on the 'Application ID' column, the result may not be in the expected desc/asc order.

Please check the recording:
https://www.loom.com/share/6b2e6282760947fe980e779b1e0c9164?sid=d5c2c9fb-4923-42e4-87fc-a2a8d5c9cdd8

**Comment by chenyulin0719** [comment]
Also checked similar behavior occurs in other columns that can be sorted on the master branch.

**Comment by chenyulin0719** [comment]
Oh,  I just realized that the sorting result is in below order after each click

1. ASC
2. DESC
3. No Sorting

looping 1~3.

**Comment by chia7712** [comment]
@chenyulin0719 thanks for the test.

We can have another ticket to discuss the sort rule (for example, keep only desc and asc sort)

Will merge it later

**Pull request merged**
