### PR TITLE
[YUNIKORN-959] Simplify partition info in the REST call

### PR DESCRIPTION
**Pull request by steinsgateted**
### What is this PR for?
Remove some information from` /ws/v1/clusters`, and add some information from `/ws/v1/partitions`

- activeNodes and runningApplications and runningContainers change to `/ws/v1/partitions` information.
- The state of applications is the same as the applications's state of YK's core

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-959

### Screenshots (if appropriate)
2023-01-24 01-53-16 的螢幕擷圖

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — COMMENTED** [review]
one nit: missing newline at the end of the file `src/app/models/cluster-info.model.ts`

**Comment by wilfred-s** [comment]
@akhilpb001 this looks good. Can you check please?

**Comment by akhilpb001** [comment]
Hi @steinsgateted could you pls also update json-db.json with latest cluster and partition json?

**Review by akhilpb001 — CHANGES_REQUESTED** [review]

**Comment by steinsgateted** [comment]
@wilfred-s @akhilpb001 Thank you for your review. Updated.

**Review by akhilpb001 — APPROVED** [review]
LGTM

**Pull request closed without merging**
